version: '3'
services:
  acmeair-db:
    container_name: acmeair-db
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - acme

  tomcat:
    container_name: acmeair-standalone-temurin
    image: acmeair-standalone-temurin
    networks:
      - acme
    ports:
      - "9080:8080"
      - "9443:8443"
      - "7777:7777"
    environment:
      - MONGO_HOST=acmeair-db
    tmpfs:
      - /tmp

networks:
  acme:
    driver: bridge
